spring:
  application:
    name: sporty-jackpot-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: jackpot-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.sporty.jackpot.model
        spring.json.value.default.type: com.sporty.jackpot.model.Bet

jackpot:
  contribution:
    percentage-rate: 5
    fixed-amount: 10
    tiered-rates:
      - threshold: 10000
        rate: 10
      - threshold: 50000
        rate: 5
      - rate: 2
  reward:
    fixed-amount: 500
    percentage-rate: 50
    probability-rate: 5
    tiered-probabilities:
      - threshold: 10000
        probability-rate: 1
      - threshold: 50000
        probability-rate: 5
      - threshold: 100000
        probability-rate: 10
      - probability-rate: 100

server:
  port: 8080

logging:
  level:
    root: INFO
    com.sporty.jackpot: DEBUG
